apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./components/external-dns/build-target
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
